### ISSUE TITLE
Where are we going with this?

### ISSUE THREAD

**Issue by InvncibiltyCloak** [rmjutras/EUROBOT#1]
This is pretty serious issue. There needs to be some sort of roadmap or high-level design document.

**Comment by rmjutras** [comment]
DO YOU HAVE A BURNING DEESIRE
TO TAKE THIS HIGHER AND HIGHER?
- [ ] THE POWER
- [ ] YOUR LOVIN'
- [ ] THE SPEED
- [ ] FLAMIN'
- [ ] ALL THROUGH THE NIGHT
- [ ] I CAN'T SURVIVE

**Comment by rmjutras** [comment]
Ok sorry. Yeah I haven't really had a chance to work on/ think about this very much lately. The general next step is to make a Markov chain model for eurobeat lyrics, but we're going to have group phrases for that to work without too much supervision.

**Comment by rmjutras** [comment]
BTW Marc - your code structure is really nice. Ugh I wish my coworkers were this neat & structured.

**Comment by InvncibiltyCloak** [comment]
Thanks! I like the wiki page that roadmaps the project.
