### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by rmjutras** [rmjutras/EUROBOT#2]
Invalid syntax error @ line 35 in the code. It looks like you got the if on the fourth line of the snippet below messed up. Just wondering what level of nesting you intended it to be at. (See LyricScraper.py line 35)
`for i, data in enumerate(pool.imap_unordered(scrape_song, urllist), 1):
        max_i = max(i, max_i)
        if i%2 == 0:
            short_artist = data.artist[:19] + ".." if 
                    len(data.artist) > 21 else data.artist`

**Comment by rmjutras** [comment]
Ahh just realized we might have Python 2.7 vs 3.3 incompatibilities?

**Comment by rmjutras** [comment]
Also having trouble with 
`import urllib.request`
Can't find that for Python 2.7? Will try running in a virtual box with Python 3.

**Comment by InvncibiltyCloak** [comment]
I changed it up to support both Python 2 and 3.

**Comment by InvncibiltyCloak** [comment]
Note that it does require a package called Beautiful Soup. Install with:
`pip install beautifulsoup4`

**Comment by rmjutras** [comment]
Great! Thanks
