### ISSUE TITLE
parallel_scrape_songs bug

### ISSUE THREAD

**Issue by rmjutras** [rmjutras/EUROBOT#4]
```
>>> songs = do_scrape()
Loading list of songs to scrape...
    4187 songs found.
Scraping songs...
Process PoolWorker-2:
Process PoolWorker-1:
Process PoolWorker-4:
Process PoolWorker-6:
Process PoolWorker-3:
Process PoolWorker-10:
Process PoolWorker-7:
Process PoolWorker-8:
Process PoolWorker-15:
Process PoolWorker-9:
Process PoolWorker-16:
Process PoolWorker-14:
Traceback (most recent call last):
  File "C:\Anaconda\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Anaconda\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda\lib\multiprocessing\pool.py", line 102, in worker
    task = get()
  File "C:\Anaconda\lib\multiprocessing\queues.py", line 376, in get
    return recv()
AttributeError: 'module' object has no attribute 'scrape_song'
```

[AttributeError is repeated]

**Comment by rmjutras** [comment]
The bug is coming from `for i, data in enumerate(pool.imap_unordered(scrape_song, urllist), 1):` I think.
(Line 47 in the version I just pushed)

Not sure if this has anything to do with it, but your function `scrape_songs` is never used. The function `scrape_song` is though. I am renaming `scrape_songs` to `scrape_song_list` for better differentiation & reflecting that in `parallel_scrape_songs` changing to `parallel_scrape_song_list`.

**Comment by InvncibiltyCloak** [comment]
Right, I know why. The multiprocessing library cannot be used from an interactive interpreter because it needs to be able to import whatever the current `__main__` module is. You will either have to run the program by itself (`python program.py`) or use the non-parallel version (`scrape_song_list`).

**Comment by rmjutras** [comment]
- [x] ok
